# -*- coding: utf-8 -*-
"""Ex1_RA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_8DL0Uf1KgUp5H26QWKgIeWbcWBHJ9OC

1. Escreva um algoritmo em Python para calcular a idade de alguém, sabendo se seu ano
de nascimento.
"""

from datetime import date

anonascimento = int(input('Digite seu ano de nascimento no fomato yyyy: '))
anoatual = date.today().year
idade = anoatual - anonascimento

print(f'Sua idade é de {idade} anos')

"""2. Escreva um algoritmo em Python para calcular o valor, em reais, que deve ser pago por
um cliente de uma locadora de carros. Sabe-se que o valor de cada carro é R$ 100,00.
Solicite ao usuário quantos carros ele gostaria de alugar e imprima o valor total da
locação de todos os carros.
"""

qdiaaluguel = int(input('Digite a quantidade de dias que você ficará com o carro: '))
valorreais = qdiaaluguel * 100

print (f'Você deve pagar R${valorreais:.2f}')

"""3. Leia do teclado a temperatura em Celsius e imprima o equivalente em Fahrenheit.
(Fórmula: (X ºC × 9/5) + 32
"""

tempc = int(input('Digite o valor da temperatura em celcius: '))
tempf = (tempc * 9/5) + 32

print(f'O valor da temperatura em fahrenheit é {tempf}')

"""4. Escrever um algoritmo para calcular a média de 4 notas."""

notas = []

for i in range(4):
    nota = float(input(f'Digite a nota {i+1}: '))
    notas.append(nota)

media = sum(notas) / len(notas)

print(f'As notas são: {notas}')
print(f'A média das notas é: {media:.2f}')

"""5. Calcular sua idade em meses."""

from datetime import date

nasc = input('Data de nascimento no formato dd/mm/aaaa: ')
dia, mes, ano = map(int, nasc.split('/'))

meses = (date.today().year - ano) * 12 + (date.today().month - mes)
if date.today().day < dia:
    meses -= 1

print(f'Sua idade em meses: {meses}')

"""6. Calcular preço de venda para produto por quilo"""

precokg = float(input('Preço por kg: '))
peso = float(input('Peso total em kg: '))

precofinal = precokg * peso

print(f'Total: R$ {precofinal:.2f}')